# Generated by Django 5.0.14 on 2025-10-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(help_text='Nombre interno de la categoría', max_length=100, unique=True, verbose_name='Nombre')),
                ('label', models.CharField(help_text='Etiqueta para mostrar en el sidebar', max_length=100, verbose_name='Etiqueta')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(help_text='Clase o nombre del ícono (ej: fa-dashboard, material-icons)', max_length=50, verbose_name='Ícono')),
                ('color', models.CharField(help_text='Color hex o nombre de clase para la categoría', max_length=20, verbose_name='Color')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Orden de visualización (menor número aparece primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activa')),
                ('is_system', models.BooleanField(default=False, help_text='Las categorías del sistema no pueden ser eliminadas', verbose_name='Categoría del sistema')),
            ],
            options={
                'verbose_name': 'Categoría de Menú',
                'verbose_name_plural': 'Categorías de Menú',
                'db_table': 'navigation_menucategory',
                'ordering': ['order', 'label'],
                'indexes': [models.Index(fields=['order'], name='navigation__order_9eccba_idx'), models.Index(fields=['is_active'], name='navigation__is_acti_1b2b24_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(help_text='Nombre interno del ítem de menú', max_length=100, verbose_name='Nombre')),
                ('label', models.CharField(help_text='Etiqueta para mostrar en el menú', max_length=100, verbose_name='Etiqueta')),
                ('url', models.CharField(help_text='Ruta o URL del ítem', max_length=255, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase o nombre del ícono', max_length=50, null=True, verbose_name='Ícono')),
                ('badge', models.CharField(blank=True, help_text='Texto de la insignia (ej: "Nuevo", "3")', max_length=50, null=True, verbose_name='Insignia')),
                ('badge_variant', models.CharField(blank=True, help_text='Color o variante de la insignia (ej: "danger", "success")', max_length=20, null=True, verbose_name='Variante de insignia')),
                ('resource_type', models.CharField(blank=True, help_text='Tipo de recurso para verificación con Cerbos', max_length=50, null=True, verbose_name='Tipo de recurso')),
                ('action', models.CharField(blank=True, help_text='Acción para verificación con Cerbos (ej: "read", "create")', max_length=50, null=True, verbose_name='Acción')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Orden de visualización dentro de la categoría', verbose_name='Orden')),
                ('is_external', models.BooleanField(default=False, verbose_name='Enlace externo')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='Abrir en nueva pestaña')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_system', models.BooleanField(default=False, help_text='Los ítems del sistema no pueden ser eliminados', verbose_name='Ítem del sistema')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='navigation.menucategory', verbose_name='Categoría')),
                ('parent', models.ForeignKey(blank=True, help_text='Ítem padre para menús jerárquicos', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem', verbose_name='Ítem padre')),
            ],
            options={
                'verbose_name': 'Ítem de Menú',
                'verbose_name_plural': 'Ítems de Menú',
                'db_table': 'navigation_menuitem',
                'ordering': ['category__order', 'order', 'label'],
            },
        ),
    ]
