# Generated by Django 5.0.14 on 2025-10-23 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('navigation', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='required_role',
            field=models.ForeignKey(blank=True, help_text='Rol mínimo requerido para ver este ítem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='permissions.role', verbose_name='Rol requerido'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category'], name='navigation__categor_04d9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent'], name='navigation__parent__eddc1c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['required_role'], name='navigation__require_56b046_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['order'], name='navigation__order_bba4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['is_active'], name='navigation__is_acti_0e1824_idx'),
        ),
    ]
