# Generated by Django 5.0.14 on 2025-10-24 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de la función (ej: "Listar Usuarios")', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único para identificar la función (ej: "users.list")', max_length=100, unique=True, verbose_name='Código')),
                ('url', models.CharField(blank=True, help_text='Ruta de la función en Angular (ej: "/users")', max_length=200, null=True, verbose_name='URL')),
                ('icon', models.CharField(default='fas fa-circle', help_text='Clase CSS del icono (ej: "fas fa-users")', max_length=100, verbose_name='Icono')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor = primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Si la función está activa o no', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Función padre para crear submenús', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.function', verbose_name='Función padre')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
                'db_table': 'navigation_functions',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='navigation__code_c7baf8_idx'), models.Index(fields=['parent', 'order'], name='navigation__parent__7a11fd_idx')],
            },
        ),
    ]
