# Generated by Django 5.0.14 on 2025-10-29 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='cerbos_resource',
            field=models.CharField(blank=True, help_text='Nombre del recurso en Cerbos (ej: "user", "role", "function", "category")', max_length=100, null=True, verbose_name='Recurso Cerbos'),
        ),
        migrations.AddField(
            model_name='function',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Las funciones del sistema no pueden ser eliminadas', verbose_name='Función del sistema'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría (ej: "Gestión de Usuarios")', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Código único para identificar la categoría (ej: "users_management")', max_length=100, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, help_text='Descripción de la categoría', null=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-folder', help_text='Clase CSS del icono (ej: "fas fa-users")', max_length=100, verbose_name='Icono')),
                ('color', models.CharField(blank=True, help_text='Color hex o nombre para la categoría (ej: "#3498db", "primary")', max_length=20, null=True, verbose_name='Color')),
                ('order', models.IntegerField(default=0, help_text='Orden de aparición en el menú (menor = primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Si la categoría está activa o no', verbose_name='Activa')),
                ('is_system', models.BooleanField(default=False, help_text='Las categorías del sistema no pueden ser eliminadas', verbose_name='Categoría del sistema')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'navigation_categories',
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['code'], name='navigation__code_bf3a3a_idx'), models.Index(fields=['order'], name='navigation__order_443f97_idx'), models.Index(fields=['is_active'], name='navigation__is_acti_2d836c_idx')],
            },
        ),
        migrations.AddField(
            model_name='function',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece esta función', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions', to='navigation.category', verbose_name='Categoría'),
        ),
    ]
