# Generated by Django 5.0.14 on 2025-10-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección completa', max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='ci',
            field=models.CharField(blank=True, db_index=True, help_text='Cédula de identidad o documento de identidad', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='Bolivia', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='profile_pictures/%Y/%m/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Empleado'), ('CUSTOMER', 'Cliente'), ('SUPPLIER', 'Proveedor'), ('OTHER', 'Otro')], default='OTHER', help_text='Clasificación del usuario en el sistema', max_length=20, verbose_name='Tipo de usuario'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ci'], name='users_user_ci_e37589_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
    ]
