# Generated by Django 5.0.14 on 2025-10-30 03:50

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_birth_date_user_ci_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('customer_code', models.CharField(db_index=True, help_text='Código único del cliente en el sistema', max_length=20, unique=True, verbose_name='Código de Cliente')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Persona Natural'), ('BUSINESS', 'Empresa')], default='INDIVIDUAL', help_text='Persona natural o empresa', max_length=20, verbose_name='Tipo de Cliente')),
                ('tax_id', models.CharField(blank=True, db_index=True, help_text='Número de identificación tributaria', max_length=50, null=True, verbose_name='RUC/NIT')),
                ('company_name', models.CharField(blank=True, help_text='Nombre de la empresa (para personas jurídicas)', max_length=255, null=True, verbose_name='Razón Social')),
                ('contact_person', models.CharField(blank=True, help_text='Nombre de la persona de contacto en la empresa', max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Límite de crédito en la moneda local', max_digits=12, verbose_name='Límite de Crédito')),
                ('payment_terms', models.IntegerField(default=30, help_text='Días de crédito para pagos (ej: 30, 60, 90)', verbose_name='Términos de Pago')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento por defecto', max_digits=5, verbose_name='Descuento (%)')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre el cliente', null=True, verbose_name='Notas')),
                ('is_active_customer', models.BooleanField(default=True, help_text='Indica si el cliente está activo para operaciones comerciales', verbose_name='Cliente Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'users_customer',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_code'], name='users_custo_custome_8def82_idx'), models.Index(fields=['tax_id'], name='users_custo_tax_id_b15a32_idx'), models.Index(fields=['is_active_customer'], name='users_custo_is_acti_c87ae3_idx'), models.Index(fields=['company_name'], name='users_custo_company_a60cec_idx')],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
