# Generated by Django 5.0.14 on 2025-10-23 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('name', models.CharField(help_text='Nombre para mostrar del rol', max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(db_index=True, help_text='Código interno del rol (ej: ADMIN, MANAGER, USER)', max_length=50, unique=True, verbose_name='Código')),
                ('description', models.TextField(help_text='Descripción detallada del rol y sus permisos', verbose_name='Descripción')),
                ('cerbos_role', models.CharField(db_index=True, help_text='Nombre del rol correspondiente en las políticas de Cerbos', max_length=100, verbose_name='Rol en Cerbos')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
                ('is_system', models.BooleanField(default=False, help_text='Los roles del sistema no pueden ser eliminados', verbose_name='Rol del sistema')),
                ('level', models.IntegerField(default=0, help_text='Nivel de jerarquía del rol (mayor número = más permisos)', verbose_name='Nivel jerárquico')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'permissions_role',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Asignado en')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Fecha de expiración de la asignación (opcional)', null=True, verbose_name='Expira en')),
                ('scope_type', models.CharField(blank=True, help_text='Tipo de recurso al que se limita el rol (ej: organization, project)', max_length=50, null=True, verbose_name='Tipo de alcance')),
                ('scope_id', models.BigIntegerField(blank=True, help_text='ID del recurso específico al que se limita el rol', null=True, verbose_name='ID del alcance')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Asignación de Rol',
                'verbose_name_plural': 'Asignaciones de Roles',
                'db_table': 'permissions_roleassignment',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
