# Generated by Django 5.0.14 on 2025-10-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_function'),
        ('permissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='functions',
            field=models.ManyToManyField(blank=True, help_text='Funciones del menú asignadas a este rol', related_name='roles', to='navigation.function', verbose_name='Funciones'),
        ),
    ]
